baseURL = "https://www.genestorian.org/"
languageCode = "en-us"
title = "Genestorian"
subtitle = "A web application for model organism collections"
theme = "bigspring-light"

[menu]
  [[menu.main]]
    identifier = "contributing"
    name = "Contributing"
    title = "Contributing"
    url = "/contributing/"
    weight = 3

  [[menu.main]]
    identifier = "internship"
    name = "Interships"
    title = "Interships"
    url = "/internship/"
    weight = 2

  [[menu.main]]
    identifier = "roadmap"
    name = "Roadmap"
    title = "Roadmap"
    url = "/roadmap/"
    weight = 1
  

[markup.goldmark.renderer]
  unsafe = true