baseURL = "http://genestorian.org/"
languageCode = "en-us"
title = "Genestorian"
subtitle = "A web application for model organism collections"
theme = "ananke"

[params]
      background_color_class = "bg-blue"
      description = "A web application for model organism collections"
      body_classes = "sans-serif"
      post_content_classes = "sans-serif"