name: github pages
on: push
jobs:
  print_context:
    if: ${{0}} # If you want to access the context
    name: Print context
    runs-on: ubuntu-latest
    steps:
    - name: Dump github context
      run:   echo "$GITHUB_CONTEXT"
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
  deploy:
    if: ${{github.event.repository.name == 'GenestorianLandingPageSource'}}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        env:
          HUGO_ENV: production # For ananke theme not to include the noindex tag
        run: hugo --minify --environment production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GENESTORIAN_SITE }}
          publish_dir: ./public
          publish_branch: master
          external_repository: manulera/manulera.github.io
          cname: www.genestorian.org